package update for CVE-2021-43138
hmcts/ccd-api-gateway pull request #430
Opened 2022-05-05 22:53 UTC by sgecici

https://tools.hmcts.net/jira/browse/CCD-3124

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-05-06 07:59 UTC, MSancaktutar approved these changes

2022-05-06 08:00 UTC, MSancaktutar requested changes
Suppression not removed. Could you pls clear up?

2022-05-06 13:54 UTC, sgecici commented
> Suppression not removed. Could you pls clear up?

we did it, thanks

2022-05-06 14:17 UTC, MSancaktutar approved these changes

2022-05-09 10:43 UTC, paulridout commented
Closing this Pull Request in favour of https://github.com/hmcts/ccd-api-gateway/pull/431.  In this case there seems to be no need to force the version of es6-promisify to version 5.0.0 as it isn't updated by the changes to async.

2022-05-09 10:43 UTC, closed without merging